### ISSUE TITLE
using arrow keys to reposition cursor does not render correctly in Safari

### ISSUE THREAD

**Issue by mp-jwolkerstorfer** [filamentgroup/formcore#69] opened 2016-09-12 10:49 UTC
Mac OS X 10.11.6, Safari 9.1.3; on the final demo at https://www.filamentgroup.com/lab/type-number.html (Also in the in-app browser of Reeder 3.0.1, same OS.)

1.  type `123123` and observe cursor at end of text
2.  hit left arrow key 3 times and observe cursor still at end of text
3.  hit `0` and see the updated text `1230123` with the cursor now appearing after the `0`

Additionally, it seems to be impossible in all browsers to use the up-arrow to go to the start of the text or the down-arrow to go to the end of the text.

**Comment by zachleat** [comment] 2016-09-12 14:26
Hmmm, I could reproduce the left-right cursor issue on Browserstack (El Capitan):
![image](https://cloud.githubusercontent.com/assets/39355/18439201/fea1bdb8-78c9-11e6-9bf0-4bae21b9b380.png)

I think the above is more a byproduct of how Browserstack repaints the remote machine (cursor movement may not be enough to trigger a repaint).

I was not able to reproduce on my local machine (El Capitan 10.11.6):
![image](https://cloud.githubusercontent.com/assets/39355/18439211/09df3ce6-78ca-11e6-92c5-3b215ee214f3.png)

Were you using a remote machine to test this? Or was it local?

As for the up-down arrow issue, this feature was never available in `type="number"` fields. Up and down arrows were previously used for increment and decrement, which `numeric-input` disables when using `data-numeric-input-nav-disabled`. I’ve filed this as a separate feature request at #70.

**Comment by mp-jwolkerstorfer** [comment] 2016-09-12 16:29
I was testing this on my local machine:
MacBook Pro (Retina, 15-inch, Mid 2014)
Processor: 2.5 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: NVIDIA GeForce GT 750M 2048 MB

**Comment by zachleat** [comment] 2016-09-23 18:10
I’m guessing this is a duplicate of #75 which @johnbender fixed. Look for it in v1.2.3.

**Comment by zachleat** [comment] 2016-09-28 21:38
v1.2.3 is out! Please retest and reopen if needed!

**Closed by zachleat** 2016-09-28 21:38 UTC
Labels: question
